//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Derby_Pub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestaurantModel : DbContext
    {
        public RestaurantModel()
            : base("name=RestaurantModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Allergen> Allergens { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Menu_Product> Menu_Product { get; set; }
        public virtual DbSet<Order_Menu> Order_Menu { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int DeleteAllergen(string allergenName)
        {
            var allergenNameParameter = allergenName != null ?
                new ObjectParameter("AllergenName", allergenName) :
                new ObjectParameter("AllergenName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAllergen", allergenNameParameter);
        }
    
        public virtual int DeleteCategory(string categoryName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCategory", categoryNameParameter);
        }
    
        public virtual int DeleteMenu(string menuName)
        {
            var menuNameParameter = menuName != null ?
                new ObjectParameter("MenuName", menuName) :
                new ObjectParameter("MenuName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMenu", menuNameParameter);
        }
    
        public virtual int DeleteProduct(string productName)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProduct", productNameParameter);
        }
    
        public virtual ObjectResult<string> GetAllCategoryes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAllCategoryes");
        }
    
        public virtual ObjectResult<string> GetAllergenFromProductName(string productName)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAllergenFromProductName", productNameParameter);
        }
    
        public virtual ObjectResult<GetAllMenusBasedOnAllergen_Result> GetAllMenusBasedOnAllergen(string categoryName, string allergenName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            var allergenNameParameter = allergenName != null ?
                new ObjectParameter("AllergenName", allergenName) :
                new ObjectParameter("AllergenName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllMenusBasedOnAllergen_Result>("GetAllMenusBasedOnAllergen", categoryNameParameter, allergenNameParameter);
        }
    
        public virtual ObjectResult<GetAllMenusWithoutAnAllergen_Result> GetAllMenusWithoutAnAllergen(string categoryName, string allergenName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            var allergenNameParameter = allergenName != null ?
                new ObjectParameter("AllergenName", allergenName) :
                new ObjectParameter("AllergenName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllMenusWithoutAnAllergen_Result>("GetAllMenusWithoutAnAllergen", categoryNameParameter, allergenNameParameter);
        }
    
        public virtual ObjectResult<GetAllProductsWihoutAnAllergen_Result> GetAllProductsWihoutAnAllergen(string categoryName, string allergenName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            var allergenNameParameter = allergenName != null ?
                new ObjectParameter("AllergenName", allergenName) :
                new ObjectParameter("AllergenName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProductsWihoutAnAllergen_Result>("GetAllProductsWihoutAnAllergen", categoryNameParameter, allergenNameParameter);
        }
    
        public virtual ObjectResult<GetAllProductWithAnAllergenBasedOnCategory_Result> GetAllProductWithAnAllergenBasedOnCategory(string category, string allegenName)
        {
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var allegenNameParameter = allegenName != null ?
                new ObjectParameter("allegenName", allegenName) :
                new ObjectParameter("allegenName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProductWithAnAllergenBasedOnCategory_Result>("GetAllProductWithAnAllergenBasedOnCategory", categoryParameter, allegenNameParameter);
        }
    
        public virtual ObjectResult<byte[]> GetImagesByProductName(string productName)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("GetImagesByProductName", productNameParameter);
        }
    
        public virtual ObjectResult<GetMenuByCategory_Result> GetMenuByCategory(string categoryName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMenuByCategory_Result>("GetMenuByCategory", categoryNameParameter);
        }
    
        public virtual ObjectResult<GetMenuDetails_Result> GetMenuDetails(string menuName)
        {
            var menuNameParameter = menuName != null ?
                new ObjectParameter("MenuName", menuName) :
                new ObjectParameter("MenuName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMenuDetails_Result>("GetMenuDetails", menuNameParameter);
        }
    
        public virtual ObjectResult<GetMenuDetaliesAboutOrder_Result> GetMenuDetaliesAboutOrder(Nullable<int> orderCode)
        {
            var orderCodeParameter = orderCode.HasValue ?
                new ObjectParameter("OrderCode", orderCode) :
                new ObjectParameter("OrderCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMenuDetaliesAboutOrder_Result>("GetMenuDetaliesAboutOrder", orderCodeParameter);
        }
    
        public virtual ObjectResult<GetOrdersFromUser_Result> GetOrdersFromUser(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrdersFromUser_Result>("GetOrdersFromUser", userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> GetPriceOfMenu(string menuName)
        {
            var menuNameParameter = menuName != null ?
                new ObjectParameter("MenuName", menuName) :
                new ObjectParameter("MenuName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetPriceOfMenu", menuNameParameter);
        }
    
        public virtual ObjectResult<GetProductBasedOnAllergens_Result> GetProductBasedOnAllergens(string categoryName, string allergenName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            var allergenNameParameter = allergenName != null ?
                new ObjectParameter("AllergenName", allergenName) :
                new ObjectParameter("AllergenName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductBasedOnAllergens_Result>("GetProductBasedOnAllergens", categoryNameParameter, allergenNameParameter);
        }
    
        public virtual ObjectResult<GetProductByCategory_Result> GetProductByCategory(string categoryName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductByCategory_Result>("GetProductByCategory", categoryNameParameter);
        }
    
        public virtual ObjectResult<GetProductDetaliesAboutOrder_Result> GetProductDetaliesAboutOrder(Nullable<int> orderCode)
        {
            var orderCodeParameter = orderCode.HasValue ?
                new ObjectParameter("OrderCode", orderCode) :
                new ObjectParameter("OrderCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDetaliesAboutOrder_Result>("GetProductDetaliesAboutOrder", orderCodeParameter);
        }
    
        public virtual ObjectResult<GetProductsByAllergen_Result> GetProductsByAllergen(string allergenName)
        {
            var allergenNameParameter = allergenName != null ?
                new ObjectParameter("AllergenName", allergenName) :
                new ObjectParameter("AllergenName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsByAllergen_Result>("GetProductsByAllergen", allergenNameParameter);
        }
    
        public virtual ObjectResult<GetProductsByMenuName_Result> GetProductsByMenuName(string menuName)
        {
            var menuNameParameter = menuName != null ?
                new ObjectParameter("MenuName", menuName) :
                new ObjectParameter("MenuName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsByMenuName_Result>("GetProductsByMenuName", menuNameParameter);
        }
    
        public virtual int InsertIntoOrder_Menu(Nullable<int> oderId, Nullable<int> menuId)
        {
            var oderIdParameter = oderId.HasValue ?
                new ObjectParameter("OderId", oderId) :
                new ObjectParameter("OderId", typeof(int));
    
            var menuIdParameter = menuId.HasValue ?
                new ObjectParameter("MenuId", menuId) :
                new ObjectParameter("MenuId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertIntoOrder_Menu", oderIdParameter, menuIdParameter);
        }
    
        public virtual int InsertIntoOrder_Product(Nullable<int> orderId, Nullable<int> productId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertIntoOrder_Product", orderIdParameter, productIdParameter);
        }
    }
}
